version: '1'

services:
  server:
    build: ./server/.
    image: chat-app-server
    ports:
      - "3001:3001"
  client:
    build: ./client/.
    image: chat-app-client
    ports:
      - "3000:3000"

    